apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer # Change this to LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 5000 # Port the container listens on
